Repository msp-strath/Mary, pull requests merged in 2020-04, with the labels that each got.

#42 [ new ] string splices
  examples/enum.gold
  examples/hello.gold
  examples/inlines.gold
  examples/splices.gold
  examples/splices.jsgold
  examples/splices.shonkier
  examples/strings.gold
  examples/strings.jsgold
  examples/strings.shonkier
  src/Data/Bwd.hs
  src/Shonkier/Parser.hs
  src/Shonkier/Pretty.hs
  src/Shonkier/Pretty/Render/Pandoc.hs
  src/Shonkier/Scope.hs
  src/Shonkier/Semantics.hs
  src/Shonkier/ShonkierJS.hs
  src/Shonkier/Syntax.hs
  src/Shonkier/Value.hs
  src/data-dir/Shonkier.js
Labels: enhancement, shonkier

#54 Forms
  examples/enum.html
  examples/forms.html
  examples/forms.input
  examples/forms.mary
  examples/hello.html
  examples/hutton.html
  examples/inlines.html
  examples/links.html
  examples/primitives.gold
  examples/primitives.jsgold
  examples/primitives.shonkier
  examples/template.html
  mary.cabal
  mary.hs
  src/Mary/Find.hs
  src/Mary/Pandoc.hs
  src/Mary/ServePage.hs
  src/Shonkier.hs
  src/Shonkier/Primitives.hs
  src/Shonkier/Semantics.hs
  src/Shonkier/Value.hs
  src/data-dir/Shonkier.js
  test/Test/Mary.hs
Labels: bikeshedding, enhancement

#70 [ fix ] parser library
  examples/hutton.html
  examples/hutton.mary
  examples/parser.gold
  examples/parser.jsgold
  examples/parser.shonkier
Labels: bug

#73 [ fix #59 ] FromValue is allowed to fail
  examples/enum.html
  examples/enum.mary
  examples/inlines.html
  examples/inlines.mary
  examples/template.html
  src/Mary/Pandoc.hs
  src/Shonkier/Pandoc.hs
  src/Shonkier/Pretty.hs
  src/Shonkier/Value.hs
Labels: bug

#74 [ new ] rendering dot graphs as inline svg
  .github/workflows/haskell.yml
  Makefile
  examples/dot.html
  examples/dot.mary
  examples/dot.sed
  examples/import-as.shonkier
  examples/imports.html
  examples/list.shonkier
  mary.cabal
  src/Mary/Pandoc.hs
  src/Mary/ServePage.hs
  src/Shonkier/Dot.hs
  src/Shonkier/Pandoc.hs
  src/Shonkier/Result.hs
  src/Shonkier/Value.hs
  test/Test/Utils.hs
Labels: enhancement
